### ISSUE TITLE
Follow ATV-PR-depends pull request

### ISSUE THREAD

**Issue by sy6sy2** [SylvainCecchetto/xbmc#19]
PR: https://github.com/xbmc/xbmc/pull/15919

**Comment by sy6sy2** [comment]
All checks have passed!

**Comment by sy6sy2** [comment]
I will add https://github.com/SylvainCecchetto/xbmc/commit/b1b800ac79e10bf687847ab76b437e62220e6bc6 and https://github.com/SylvainCecchetto/xbmc/commit/61c87ef77ea0383e202e473d718bb78eda57b773 to the PR today.

**Comment by phunkyfish** [comment]
Posted in the forum but should have posted here:

Looks like the Leia branch has been created. Should mean depends changes should be possible to merge soon. @SylvainCecchetto can you check if any of the latest commits need to added to the ATV-Depends branch?

We should be good after those and the fix from @fuzzard for multi-threaded builds when ready.

**Comment by sy6sy2** [comment]
I just replied on the forum ;-)

**Comment by phunkyfish** [comment]
Review on this PR just posted.

**Comment by sy6sy2** [comment]
Yep! I will try to resolve most of the "issues" pointed by Rechi

**Comment by fuzzard** [comment]
a rebase on master should fix (with some minor touchups) a number of the issues around the issues he brought up for the following

`xbmc/platform/darwin/osx/network            platform/osx/network`
`xbmc/platform/darwin/osx/peripherals      platform/osx/peripherals`
`xbmc/platform/darwin/osx/powermanagement platform/darwin/osx/powermanagement`
`xbmc/platform/darwin/osx/storage            platform/osx/storage`

a commit by Rechi himself was merged that relocates the above from the osx down to darwin level folders

**Comment by sy6sy2** [comment]
I resolved obvious issues and rebase with upstream/master.
Still some issues and questions.

**Comment by sy6sy2** [comment]
I will update tools/depends/configure.ac according to the comment.

**Comment by sy6sy2** [comment]
I will move tvOS windowing into separate folder like Rechi did for iOS here https://github.com/xbmc/xbmc/commit/5f4b47ad8c012b8de47ef3f212ca1f1db028e48c
(Hope I will not break anything)
Edit: This modification impact also Kodi C++ sources files (move and rename files).
But this PR is not intended to treat about Kodi core :-/
What is our plan concerning this modification?

**Comment by fuzzard** [comment]
I would have followed it up as core changes were PR'd, but if he wants it done before a merge, probably have to go with it.

**Comment by sy6sy2** [comment]
Maybe I misunderstand your answer. Do I have to apply modification on `cmake/treedata/tvos/subdirs.txt` file (like iOS) but without pushing `xbmc/*` modifications?

**Comment by fuzzard** [comment]
the windowing change requested would need to be done just the way the IOS one rechi did was. 

The other 4 (network, peripherals, powermanagement, storage) have already been done and merged by rechi, so the changes would just be to update the subdirs.txt file for those to as an example

`xbmc/platform/darwin/network platform/network`

I would inquire if they would let the windowing/osx change be done in a followup commit when further core changes are PR'd.

**Comment by sy6sy2** [comment]
Ok, I updated subdirs.txt on the PR branch.

It remains "Why make tvOS a complete separate platform rather than a special variant of the iOS platform, like it was done before?" question.

**Comment by phunkyfish** [comment]
I think it was @Memphiz who said to separate it out. I'm not sure how else to differentiate the platforms if we don't do this. 

If you have examples of where this is needed maybe that will be sufficient explanation for Rechi. Or he may be suggest a cleaner alternative to distinguish between iOS and tvOS.

**Comment by sy6sy2** [comment]
This is here https://forum.kodi.tv/showthread.php?tid=312805&pid=2842516#pid2842516

**Comment by fuzzard** [comment]
i tried a quick revert back to platform_os="ios" for tvos, and it doesnt play nice with the following errors. i assume it will be a cflag somewhere that we set via the tvos platform_os with the current PR

In file included from crypto/async/arch/../async_locl.h:30:
crypto/async/arch/../arch/async_posix.h:45:13: error: 'setcontext' is unavailable: not available on tvOS
            setcontext(&n->fibre);

I know someone came across that early on in the piece, but i dont really know why not to split them as memphiz said the way its been done. Whats the benefit to keep it as a special variant? I dont quite grasp all of the cmake nuances, so maybe rechi can shed some light as to why?

**Comment by sy6sy2** [comment]
I am agree with you. Most of dependencies are build in the same way on iOS or tvOS but there is exception like openSSL.

**Comment by fuzzard** [comment]
`ifeq ($(OS), tvos)`
` # Need to add "no-async" to avoid "'setcontext' is unavailable: not available on tvOS" error`
` CONFIGURE=./Configure iphoneos-cross no-shared zlib no-asm no-async --prefix=$(PREFIX)`
`endif`

so, it was just the no-async flag in the configure command that we set. $(OS) is the platform_os we set, so that ifeq would need to differentiate between ios/tvos some other way if we go rechi's suggested way. ~~As far as i can see, we dont keep any other variable we can call on that differentiates cleanly that its tvos. I guess you could go the route of if cpu and something else, but seems a worse path to me.~~

edit: i do see a way.

tools/target/depends/openssl/Makefile

`ifeq ($(TARGET_PLATFORM), appletvos)`
`  # Need to add "no-async" to avoid "'setcontext' is unavailable: not available on tvOS" error`
`  CONFIGURE=./Configure iphoneos-cross no-shared zlib no-asm no-async --prefix=$(PREFIX)`
`endif`


`	# Stolen pathes here: https://gist.github.com/felix-schwarz/c61c0f7d9ab60f53ebb0 `
`	if test "$(TARGET_PLATFORM)" = "appletvos"; then \`
`		sed -E -ie "s|^CFLAGS=-|CFLAGS=$(CFLAGS) -|" "$(PLATFORM)/Makefile"; \`

**Comment by sy6sy2** [comment]
In the yab branch, Memphiz sets `platform_os` to iOS for both Apple TV and iPhone.
But he sets `target_platform` to appletvos or iphoneos and he uses this variable in case the build step need to be different for iOS or tvOS.
https://github.com/Memphiz/xbmc/blob/yab/tools/depends/configure.ac

**Comment by fuzzard** [comment]
yeah, exactly what i just found. Happy to go with that if thats what they want.

**Comment by phunkyfish** [comment]
Doing it the same way as Memphiz means most of the binary addons would not need to be changed as they would compile as is for iOS.

**Comment by phunkyfish** [comment]
Also no need to modify p8platform etc. It's much cleaner.

**Comment by sy6sy2** [comment]
Why not!

**Comment by fuzzard** [comment]
Will reduce the diff down quite drastically as well, which is a good thing. A lot of stuff was duplicated with no apparent changes required (except openssl). We can just work off the target_platform for any future requirements

**Comment by sy6sy2** [comment]
Yep!
Have you already started to apply this modification? (In order to avoid working on the same thing)

**Comment by fuzzard** [comment]
Ill leave to you, happy to review though.

**Comment by phunkyfish** [comment]
I asked Memphiz under the PR for his thoughts. It would be a shame to do this work and then undo again if he has a good reason to split instead.

**Comment by sy6sy2** [comment]
Good idea to ask him about that.
According to its answer I will try to apply modification tonight on the ATV branch.

**Comment by phunkyfish** [comment]
Are there many core changes which are dependent on os_platform?

We use CORE_PLATFORM_NAME_LC and CORE_SYSTEM_NAME in the cmake files for kodi core. I assume they are set using os_platform currently and would need to change to target_platform if the direction is to change it.

**Comment by sy6sy2** [comment]
Is one of you have an idea on how things works for Android? I suppose that Kodi works on both Android TV and Android smartphone no? Is it comparable as iOS and tvOS choices?

**Comment by Memphiz** [comment]
I’s Say do as it has less impact. If my former approach is better - then go that route - just disregard my comment on the other PR then. Those are just facts about the differences. Build system side is pretty similar between iOS and tvOS - if introduction of platform_os means all the binary add on stuff needs adaption then this is a bad idea indeed.

**Comment by Memphiz** [comment]
Android is a single platform - doesn’t matter if android tv or not

**Comment by phunkyfish** [comment]
Thanks for the quick response 😉

**Comment by sy6sy2** [comment]
Thank for your answer. My english is not perfect but if I understand correctly and according to what we know; it's better to use the same platform_os for iPhone and Apple TV (at lest for dependencies and binary addons)?

**Comment by phunkyfish** [comment]
> Thank for your answer. My english is not perfect but if I understand correctly and according to what we know; it's better to use the same platform_os for iPhone and Apple TV (at lest for dependencies and binary addons)?

Yes, that is also my understanding.

**Comment by fuzzard** [comment]
@SylvainCecchetto just for reference, (and i couldnt sleep), ive whipped up a quick commit with all the changes to go back to the single ios platform. I dont have it neat and tidy across the several commits of your original, so probably just easier to use as a reference and confirmation more than anything as you redo.

https://github.com/fuzzard/xbmc/commit/7c036b5027732ddc152f514f7e93364a69abce28

There are some changes that i believe are better than the original, but they are minor things (iphoneossim in configure.ac) Im running a single threaded build whilst i go to sleep, fingers crossed it goes all nice.

**Comment by phunkyfish** [comment]
So CORE_SYSTEM_NAME is used in kodi core to differentiate iOS and tvOS.  It’s also used the binary adddon cmake files. So binary addons changes may be needed regardless.

**Comment by fuzzard** [comment]
That isnt a problem Phunky. If you rework Toolchain.cmake.in as below, it sets core_system_name based on our platform. Should be all good

tools/depends/target/Toolchain.cmake.in

`elseif(OS STREQUAL ios)`
`  set(CMAKE_SYSTEM_NAME Darwin)`
`  if(PLATFORM STREQUAL appletvos)`
`    set(CORE_SYSTEM_NAME tvos)`
`  else()`
`    set(CORE_SYSTEM_NAME ios)`
`  endif()`
`endif()`

**Comment by Memphiz** [comment]
I didn’t change anything in pvr addons in the yab branch for example ...

**Comment by phunkyfish** [comment]
Cool

**Comment by phunkyfish** [comment]
But in addons like visualisation.waveform there is cmake like this:

`if(NOT CORE_SYSTEM_NAME STREQUAL ios)
`
which would need to change to:

`if(NOT CORE_SYSTEM_NAME STREQUAL ios AND NOT CORE_SYSTEM_NAME STREQUAL tvos)`

**Comment by phunkyfish** [comment]
This is ok, and PVR addons would not change I don't think.

**Comment by phunkyfish** [comment]
@SylvainCecchetto should probably move the dist clean for binary addons to a different PR as it’s not related to depends.

**Comment by sy6sy2** [comment]
Thank you @fuzzard for your reference commit.
I will begin work on that thing in a few hours.

Ok for the dict clean of binary addon. I will remove it from this PR.

**Comment by kambala-decapitator** [comment]
what about the defines `TARGET_DARWIN_IOS` and `TARGET_DARWIN_TVOS`? Will they be completely separate or ATV will have both? If separate, then maybe it makes sense to add a "parent" define like `TARGET_DARWIN_EMBEDDED` that will be defined for both iOS and tvOS? This would help to get rid of rather ugly `#if defined(TARGET_DARWIN_IOS) || defined(TARGET_DARWIN_TVOS)`.

**Comment by phunkyfish** [comment]
I’m not sure the embedded define is a good idea. It should be obvious if something is iOS or tvOS or both. Embedded infers a meaning beyond iOS and tvOS (not that there is anything else).

That’s merely my opinion though.

**Comment by sy6sy2** [comment]
I modified the ATV-PR-depends according to https://github.com/fuzzard/xbmc/commit/7c036b5027732ddc152f514f7e93364a69abce28.
I also removed the clean/distclean addition of binary-addons.

Hope I did not break anything.

If everything is ok for you we will need to apply these changes to ATV branch?

**Comment by fuzzard** [comment]
Looks ok, except the windowing change. But I guess the point is the depends and not the Kodi build, so hopefully should be ok for now.

Think there will be a couple nit picks about new lines at end of some files, the removal of that dependency for firmware in the Deb control file, and maybe an indentation change on configure.ac.

**Comment by phunkyfish** [comment]
@SylvainCecchetto your last force push of this was incorrect. It looks like something weird happened in the rebase.

**Comment by sy6sy2** [comment]
Yep, I am currently fix all the things reviewed by Rechi. But I will rebase with upstream/master at the end ;-)

**Comment by sy6sy2** [comment]
Don't know if it's a good solution, but, in order to make things easier I only commit the minimal things in the PR in order to build tools/target and the toolchain modifications.

Maybe I am wrong all the changes in cmake/* are only useful to build core right?

**Comment by phunkyfish** [comment]
Yes, I don’t think you need those right now.

He did request to leave the build doc till a later PR, until we have a fully working ported version.

**Comment by sy6sy2** [comment]
Ok thank you!
Consequently, the PR is smaller ;-)
I will try to re compile all dependencies with the ATV-PR-depends branch to check if I forget something.

**Comment by phunkyfish** [comment]
Good idea, if you need me to test anything just ask.

**Comment by sy6sy2** [comment]
Thank you, I am currently compiling dependencies (in single thread to avoid MT related error).

**Comment by sy6sy2** [comment]
"Dependencies built successfully" with https://github.com/SylvainCecchetto/xbmc/tree/ATV-PR-depends current state

**Comment by phunkyfish** [comment]
Nice, well done. Let me review the PR

**Comment by phunkyfish** [comment]
BTW, it can take a lot of reviews to get a PR merged. Worth in the end though. Kudos for keeping at it.

**Comment by sy6sy2** [comment]
No problem, I am very patient ;-)

**Comment by phunkyfish** [comment]
The build doc is still in the PR.

**Comment by phunkyfish** [comment]
Other than that it looks good to me @SylvainCecchetto 

I will also build this to check it.

**Comment by sy6sy2** [comment]
Yes I left it but I removed the link to it in `docs/README.md` file.
Do you think that we need to completely remove the doc from the PR?

**Comment by phunkyfish** [comment]
Let’s see what Rechi says.

**Comment by phunkyfish** [comment]
Maybe just leave that comment in the PR and ask him would he prefer it removed.

**Comment by phunkyfish** [comment]
Maybe just remove the doc for now and see does that allow the PR to build.

**Comment by sy6sy2** [comment]
I will leave a comment to ask ;)

**Comment by phunkyfish** [comment]
Not sure what is going on with Jenkins.

**Comment by phunkyfish** [comment]
I have a different PR and it’s building ok.

**Comment by sy6sy2** [comment]
It seems that doing a force push when Jenkins is still building something sometimes break it :-/
With an empty commit I am randomly able to re trigger it correctly...

**Comment by phunkyfish** [comment]
Good to know. I will avoid that Scenario in the future. I don’t think Rechi will review again until Jenkins passes so you may need to do something to kick it off again.

**Comment by sy6sy2** [comment]
So, my empty commit was able to trigger again Jenkins but it is stuck with "Pending — Yeah yeah I'll start on it when I get some time." since 6 hours :-/

**Comment by phunkyfish** [comment]
Yeah, mine was the same but just recently started. It will start eventually.

**Comment by phunkyfish** [comment]
I had an error on building the dependencies:

`
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C appletvos12.2_arm64-target-debug
Detected changed: Configure
Reconfiguring...
perl ./Configure reconf
Reconfiguring with: iphoneos-cross no-shared zlib no-asm no-async --prefix=/Users/Shared/xbmc-depends/appletvos12.2_arm64-target-debug
    CC = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
    BUILDFILE = Makefile
Configuring OpenSSL version 1.1.0h (0x1010008fL)
    no-asan         [default]  OPENSSL_NO_ASAN
    no-asm          [option]   OPENSSL_NO_ASM
    no-async        [option]   OPENSSL_NO_ASYNC
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-dynamic-engine [forced]  
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-shared       [option]  
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib-dynamic [default] 
Configuring for iphoneos-cross
CC            =/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CFLAG         =-O3 -D_REENTRANT -isysroot $(CROSS_TOP)/SDKs/$(CROSS_SDK) -fno-common 
SHARED_CFLAG  =-fPIC
DEFINES       =ZLIB DSO_DLFCN HAVE_DLFCN_H NDEBUG OPENSSL_THREADS OPENSSL_NO_DYNAMIC_ENGINE OPENSSL_PIC
LFLAG         =
PLIB_LFLAG    =-Wl,-search_paths_first
EX_LIBS       =-lz 
APPS_OBJ      =
CPUID_OBJ     =mem_clr.o
UPLINK_OBJ    =
BN_ASM        =bn_asm.o
EC_ASM        =
DES_ENC       =des_enc.o fcrypt_b.o
AES_ENC       =aes_core.o aes_cbc.o
BF_ENC        =bf_enc.o
CAST_ENC      =c_enc.o
RC4_ENC       =rc4_enc.o rc4_skey.o
RC5_ENC       =rc5_enc.o
MD5_OBJ_ASM   =
SHA1_OBJ_ASM  =
RMD160_OBJ_ASM=
CMLL_ENC      =camellia.o cmll_misc.o cmll_cbc.o
MODES_OBJ     =
PADLOCK_OBJ   =
CHACHA_ENC    =chacha_enc.o
POLY1305_OBJ  =
BLAKE2_OBJ    =
PROCESSOR     =
RANLIB        =ranlib -c
ARFLAGS       =
PERL          =perl

THIRTY_TWO_BIT mode
BN_LLONG mode
RC4 uses unsigned char

Configured for iphoneos-cross.
**************************************************
***                                            ***
***   Please run the same make command again   ***
***                                            ***
**************************************************
make[3]: *** [configdata.pm] Error 1
make[2]: *** [appletvos12.2_arm64-target-debug/libssl.a] Error 2
make[1]: *** [openssl] Error 2
make: *** [target/.installed-appletvos12.2_arm64-target-debug] Error 2
```
`

And when I rerun the make command:

`/Applications/Xcode.app/Contents/Developer/usr/bin/make -C openssl
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C appletvos12.2_arm64-target-debug
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _all
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -I. -Icrypto/include -Iinclude -DZLIB -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/Shared/xbmc-depends/appletvos12.2_arm64-target-debug/ssl\"" -DENGINESDIR="\"/Users/Shared/xbmc-depends/appletvos12.2_arm64-target-debug/lib/engines-1.1\"" -O3 -D_REENTRANT -isysroot /SDKs/ -fno-common  -fPIC -MMD -MF crypto/aes/aes_cbc.d.tmp -MT crypto/aes/aes_cbc.o -c -o crypto/aes/aes_cbc.o crypto/aes/aes_cbc.c
clang: warning: no such sysroot directory: /SDKs/ [-Wmissing-sysroot]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -I. -Icrypto/include -Iinclude -DZLIB -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/Shared/xbmc-depends/appletvos12.2_arm64-target-debug/ssl\"" -DENGINESDIR="\"/Users/Shared/xbmc-depends/appletvos12.2_arm64-target-debug/lib/engines-1.1\"" -O3 -D_REENTRANT -isysroot /SDKs/ -fno-common  -fPIC -MMD -MF crypto/aes/aes_cfb.d.tmp -MT crypto/aes/aes_cfb.o -c -o crypto/aes/aes_cfb.o crypto/aes/aes_cfb.c
clang: warning: no such sysroot directory: /SDKs/ [-Wmissing-sysroot]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -I. -Icrypto/include -Iinclude -DZLIB -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/Shared/xbmc-depends/appletvos12.2_arm64-target-debug/ssl\"" -DENGINESDIR="\"/Users/Shared/xbmc-depends/appletvos12.2_arm64-target-debug/lib/engines-1.1\"" -O3 -D_REENTRANT -isysroot /SDKs/ -fno-common  -fPIC -MMD -MF crypto/aes/aes_core.d.tmp -MT crypto/aes/aes_core.o -c -o crypto/aes/aes_core.o crypto/aes/aes_core.c
clang: warning: no such sysroot directory: /SDKs/ [-Wmissing-sysroot]
crypto/aes/aes_core.c:39:10: fatal error: assert.h file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
make[4]: *** [crypto/aes/aes_core.o] Error 1
make[3]: *** [all] Error 2
make[2]: *** [appletvos12.2_arm64-target-debug/libssl.a] Error 2
make[1]: *** [openssl] Error 2
make: *** [target/.installed-appletvos12.2_arm64-target-debug] Error 2`

**Comment by sy6sy2** [comment]
This is `fatal error: 'assert.h' file not found #include <assert.h>`.
I randomly have this one too. Don't know why.

Last time, by doing `./configure` once again and make clean openssl then make openssl I was able to build openssl :-/

**Comment by phunkyfish** [comment]
Ya, this is the same issue that happens in multithreaded build I think: https://github.com/SylvainCecchetto/xbmc/issues/23

**Comment by phunkyfish** [comment]
New review from Rechi on PR

**Comment by sy6sy2** [comment]
Yep! I am currently working on it ;-)

**Comment by sy6sy2** [comment]
PR approved by Rechi! ;-)
Edit: Just to be sure, I will try to rebuild deps from scratch with this branch

**Comment by phunkyfish** [comment]
Well done!

**Comment by sy6sy2** [comment]
`Dependencies built successfully.` with `make -j4`

Next steps?:
* Merge the ATV-PR-Depends branch to ATV branch --> https://github.com/SylvainCecchetto/xbmc/issues/38
* Wait until this PR is merged

**Comment by kambala-decapitator** [comment]
great job guys!

**Comment by phunkyfish** [comment]
Wait for the PR to be be merged. In the meantime are there unrelated smaller PRs we can do. Like distclean for binary addons etc. 

So the last larger PR can just be kodi core.

**Comment by sy6sy2** [comment]
Merged!

What's next? Create a little PR for distclean binary addons? Merge ATV-PR-Depends branch to ATV branch?

Maybe can we close this issue once we know what t do next?

**Comment by phunkyfish** [comment]
I would say both. But I think you want to rebase instead of merge. Might be safer to create a new ATV branch from upstream master and cherry pick the commits over.

Not sure what will be easiest but having ATV as a reference might be useful.

**Comment by fuzzard** [comment]
yeah, id probably look to cherry pick from the current ATV into a fresh branch pulled from master just so we have a working build that can be worked on my kambala/others in the interim.

distclean PR could be useful, are there any other depends/cmake fixes not directly related to tvos we have put in place?

**Comment by sy6sy2** [comment]
* We can open another issue to follow the future distclean binary-addons PR
* I don't remember who, but one of you saw an error in the iOS build doc concerning a wrong path (if I remember correctly something with `$KODI/build`? Also create an issue to follow this future PR?
* Let me try to see if I understand correctly:
    1. Remove ATV-PR-depends branch now that this one is merged
    2. Create a fresh branch (ATV-core) from upstream/master
    3. Cherry-pick commits/changes from ATV branch to ATV-core branch (that way we are sure to not break works done on ATV branch)
Is it correct?

**Comment by fuzzard** [comment]
Dont worry about the issue for distclean. Ill send a PR to master with it. No need to track here.
Pretty sure kambala found a difference when using xcodebuild for the build instructions.

Yeah, thats how id do it.

The question i have is how you'd arrange the commits. Do we just do a big single one, or do we try and split it up into relevant parts? Obviously the smaller commits makes easier for review, but each commit should be made in a logical order to accomplish a successful build which will be a bit painful i imagine.

**Comment by sy6sy2** [comment]
Thank you for the distclean PR.

Absolutely no idea :-/
Pretty sure that we need to firstly commit changes of Toolchain.
But after that .... Maybe a commit for each "part" of libkodi?
But it seems difficult to highlight a specific order no?

**Comment by fuzzard** [comment]
Yeah, and doing it as a single large commit i think will get held up in review for ages.

Ill have a look tomorrow, see if i can think of a plan of attack.

**Comment by kambala-decapitator** [comment]
I think that we should split kodi core changes into logical parts, e.g. native app, audio sink, video rendering, system info etc.

**Comment by phunkyfish** [comment]
Agreed @kambala the order is not so important for most things. Toolchain obviously first.
