### ISSUE TITLE
App icon, launch image and top shelf extension for tvOS

### ISSUE THREAD

**Issue by phunkyfish** [SylvainCecchetto/xbmc#21]
Just create/request and add them

**Comment by kambala-decapitator** [comment]
proper launch image is located at https://github.com/xbmc/xbmc/blob/master/media/splash.jpg, but it's only 1080p (4k requires 2160p). Do you think we can request kodi team to create 2160p as well or let's just upscale existing one when generating Xcode project / packaging app bundle?

also found a forum thread with various launch images including 2160p, but they don't contain version text: https://forum.kodi.tv/showthread.php?tid=209706

**Comment by phunkyfish** [comment]
It’s probably fine as 1080p. I would imagine the upscaling would be decent on a static image.

**Comment by phunkyfish** [comment]
Although no harm in asking.

**Comment by phunkyfish** [comment]
What format/resolution are required for the different images we need? 

If we are going to ask for images might as well request them all at once.

**Comment by kambala-decapitator** [comment]
* launch image: 1080p ok / 2160p great (`sips` command can upscale)
* app icon: 1280x768 ok / 2560x1536 great (also 400x240 / 800x480, but that can be easily created with `sips` from the bigger one)

PNG is preferred (or maybe even required), but again `sips` can handle that.

**Comment by phunkyfish** [comment]
Too shelf extension can be ported from tab branch. It’s defaults to latest movies and TV but only works for paid dev account and jailbroken.

**Comment by kambala-decapitator** [comment]
I have progress with app icons and launch image, will prepare commit tomorrow

**Comment by phunkyfish** [comment]
@kambala-decapitator you happy for this to be closed?

**Comment by phunkyfish** [comment]
I can create a separate issue for having the top shelf used for latest movies and TV ported from YAB branch?

**Comment by kambala-decapitator** [comment]
yes, I also thought about separate issue for top shelf, please create. Currently working on it.

we already have all the code, now it's just a matter of cmake configuration to set up extension target.

this can be closed then.

**Comment by phunkyfish** [comment]
https://github.com/SylvainCecchetto/xbmc/issues/46

Created for extension work
