### ISSUE TITLE
[tvOS] add jenkins buildsteps

### ISSUE THREAD

**Issue by kambala-decapitator** [SylvainCecchetto/xbmc#29]
check **tools/buildsteps** folder

**Comment by sy6sy2** [comment]
It should be similar to iOS isn't it?
If nobody is on it I will try to start doing something.

**Comment by sy6sy2** [comment]
A first draft: a305a03c27a8319dbe6bd3158c0f2b6dc1f4e98a

**Comment by fuzzard** [comment]
Have drafted up another version in the main branch ive been keeping.

https://github.com/fuzzard/xbmc/blob/master_darwin-embedded-ATV/docs/README.tvOS.md#6-build-kodi

Will want it to be looked over, and updated, so if anyone is keep on the docs side of things, feel free to PR.

**Comment by fuzzard** [comment]
Last message was in the wrong thread, my bad

https://github.com/fuzzard/xbmc/commit/9495e52de54a8cf0bbec5c92a561a4bb2d935f77

I think this should work on jenkins. I dont really have a way to test until we can get everything going into master, but the theory should be sound.

**Comment by kambala-decapitator** [comment]
Based on the Slack discussion, this is already done?

**Comment by fuzzard** [comment]
Yeah
