### ISSUE TITLE
[ATV branch] Use platform_os=ios + target_platform=appletvos like in ATV-PR-depends branch

### ISSUE THREAD

**Issue by sy6sy2** [SylvainCecchetto/xbmc#38]
Just to remember that we have to cherry-pick commits from https://github.com/xbmc/xbmc/pull/15919  in the ATV branch at some time.

**Comment by sy6sy2** [comment]
Maybe it's safer to not touch at ATV branch with this modification.
This change is already present in ATV-core branch (https://github.com/SylvainCecchetto/xbmc/issues/42)

**Comment by phunkyfish** [comment]
Yes, I think we close this issue, once the next PR is merged this will not be required. ATV can stay untouched.

**Comment by phunkyfish** [comment]
Closing as this has moved to fuzzards branch.
