### ISSUE TITLE
Kodi slack

### ISSUE THREAD

**Issue by phunkyfish** [SylvainCecchetto/xbmc#39]

**Comment by phunkyfish** [comment]
@fuzzard & @kambala-decapitator

They have a slack channel for us to join for dev talk. If you’d like to join just pm me your email addresses on the kodi forum.

**Comment by fuzzard** [comment]
Pm sent

**Comment by phunkyfish** [comment]
Cool, i’ve sent onto the admin.

**Comment by kambala-decapitator** [comment]
also PMed

**Comment by phunkyfish** [comment]
Sent to admin
