### ISSUE TITLE
ATV-cmake-generation branch: next PR

### ISSUE THREAD

**Issue by sy6sy2** [SylvainCecchetto/xbmc#42]
## ATV-cmake-generation branch
* **Branch:** https://github.com/SylvainCecchetto/xbmc/tree/ATV-cmake-generation
* **PR:** https://github.com/xbmc/xbmc/pull/15956

## Description

Branch to use for the next PR to upstream/master.

This branch must be kept up to date with upstream/master by using:
```bash
git fetch upstream
git rebase upstream/master
git push --force
```

The only purpose of the modifications made by this branch is to be able to generate without error the project Xcode with Cmake for the Apple TV.
Here we do not care if we can compile or not this project with Xcode

## Commits

1. [tvOS] Toolchain: Only `tools/depends/target/Toolchain.cmake.in` file changes
2. [tvOS] cmake/platform
3. [tvOS] cmake/scripts
4. [tvOS] cmake/modules/FindOpenGLES.cmake
5. [tvOS] tools/darwin/packaging
6. [tvOS] xbmc/platform/darwin
7. *At this point I am able to generate Xcode project for tvOS without error*

**Comment by phunkyfish** [comment]
Is the plan to add each of the logical pieces from here? 

Or to submit this PR up to being able to generate the Xcode project?

**Comment by sy6sy2** [comment]
Good question, I don't which of the two solutions is the best.

**Comment by phunkyfish** [comment]
Either do I. I guess smaller is better and if anything fundamental changes in review there would be less rework.

**Comment by sy6sy2** [comment]
I think you are right.
So the plan would be to submit a PR having as only goal to be able to generate the kodi Xcode project for tvOS with tvOS toolchain. Then we we do not care if we can compile or not this project with Xcode.

If it is right I can:
1. Rename this branch to ATV-cmake-generation
2. Only keep commits from 1 to 6 (the minimal changes to be able to generate the Xcode project)
3. Open a PR if nothing is missing.

Sounds good? :-)

**Comment by phunkyfish** [comment]
Perfect

**Comment by sy6sy2** [comment]
PR open!

**Comment by kambala-decapitator** [comment]
#21 would also fit here

**Comment by sy6sy2** [comment]
You are right kambala! Never used `sips` but I can look at that

**Comment by kambala-decapitator** [comment]
shouldn't tvOS condition be added here as well? https://github.com/SylvainCecchetto/xbmc/blob/ATV-cmake-generation/cmake/scripts/osx/Macros.cmake#L23

**Comment by sy6sy2** [comment]
Oh you are right, I miss this one :-/ Thank you!
I will apply changes tomorrow.

**Comment by kambala-decapitator** [comment]
https://github.com/SylvainCecchetto/xbmc/blob/ATV-cmake-generation/cmake/scripts/tvos/ArchSetup.cmake#L38

this must be `set(CMAKE_XCODE_ATTRIBUTE_TVOS_DEPLOYMENT_TARGET "11.0")` (yes, I'm lazy to create a PR)

**Comment by kambala-decapitator** [comment]
also this: https://github.com/SylvainCecchetto/xbmc/blob/ATV-cmake-generation/CMakeLists.txt#L342

**Comment by sy6sy2** [comment]
Done, thank you for your review

**Comment by sy6sy2** [comment]
Rechi comment: "I still think making tvos a complete separate platform is the wrong approach, but I would have to see the whole code to make a final decision." about `set(CORE_SYSTEM_NAME tvos)` in the Toolchain.

Do you think that we can keep `set(CORE_SYSTEM_NAME ios)` even for tvOS and still have `TARGET_DARWIN_TVOS` in core source files?

**Comment by phunkyfish** [comment]
Even though the build systems are similar I think that core wise it will diverge over time. 

What approach is used in the yab branch?

**Comment by sy6sy2** [comment]
The yab branch uses `#if defined(TARGET_DARWIN_IOS) || defined(TARGET_DARWIN_TVOS)` approach in source files.
But there is no cmake folder in root folder because Memphiz directly uses a "custom" Xcode project

**Comment by sy6sy2** [comment]
Ok, I think that Rechi wants that we use the same approach as Raspberry (see existing Toolchain file) by using the `CORE_PLATFORM_NAME ` variable.

I think something like that:

```cmake
[...]
elseif(OS STREQUAL ios)
  set(CMAKE_SYSTEM_NAME Darwin)
  set(CORE_SYSTEM_NAME ios)
  if(PLATFORM STREQUAL appletvos)
    set(CORE_PLATFORM_NAME appletvos)
  endif()
[...]
```

instead of:

```cmake
[...]
elseif(OS STREQUAL ios)
  set(CMAKE_SYSTEM_NAME Darwin)
  if(PLATFORM STREQUAL appletvos)
    set(CORE_SYSTEM_NAME tvos)
  else()
    set(CORE_SYSTEM_NAME ios)
  endif()
[...]
```

With this approach we have nothing to modify everywhere there is a `if(CORE_SYSTEM_NAME STREQUAL ios)` and we only need to apply modification where there is a difference between tvOS and iOS.

What do you think about that?

**Comment by phunkyfish** [comment]
Sounds good 👍

**Comment by phunkyfish** [comment]
What is CORE_PLATFORM_NAME set to for iOS?

**Comment by sy6sy2** [comment]
I think this variable is currently not set for iOS

**Comment by phunkyfish** [comment]
Should we ask Rechi this on the PR?

EDIT: you already did 😉

**Comment by kambala-decapitator** [comment]
> The yab branch uses `#if defined(TARGET_DARWIN_IOS) || defined(TARGET_DARWIN_TVOS)` approach in source files

no, it's not entirely true. In yab both `TARGET_DARWIN_IOS` and `TARGET_DARWIN_TVOS` are defined for tvOS, that's why much less code changes were required.

**Comment by phunkyfish** [comment]
@kambala-decapitator

Do you like this approach:

```
[...]
elseif(OS STREQUAL ios)
  set(CMAKE_SYSTEM_NAME Darwin)
  set(CORE_SYSTEM_NAME ios)
  if(PLATFORM STREQUAL appletvos)
    set(CORE_PLATFORM_NAME appletvos)
  endif()
[...]```

**Comment by kambala-decapitator** [comment]
@phunkyfish I have no problem with it, as I'm not a fan of cmake at all :) whatever others think is best, I agree. The only thing: shouldn't CORE_PLATFORM_NAME be `tvos`, not `appletvos`?

I'm more interested in source code defines/macros.

**Comment by sy6sy2** [comment]
> no, it's not entirely true. In yab both TARGET_DARWIN_IOS and TARGET_DARWIN_TVOS are defined for tvOS, that's why much less code changes were required.

Oh yes! Maybe can we follow this approach and also define TARGET_DARWIN_IOS and TARGET_DARWIN_TVOS in our case?

> @phunkyfish I have no problem with it, as I'm not a fan of cmake at all :) whatever others think is best, I agree. The only thing: shouldn't CORE_PLATFORM_NAME be tvos, not appletvos?

Maybe, absolutely no idea which one is best ;-)

**Comment by kambala-decapitator** [comment]
> Maybe can we follow this approach and also define TARGET_DARWIN_IOS and TARGET_DARWIN_TVOS in our case?

I don't like this approach tbh, that's why I once mentioned adding a "parent" define for both. But then in some review rechi reminded of the SDK-defined `TARGET_OS_IPHONE` which is set for both iOS and tvOS, so I think this is the way to go in the sources instead of the currently used "iOS or tvOS" approach. Unless kodi code style requires using only custom defines...

Although, considering that tvOS would be a "variant" of iOS, the yab approach sounds valid.

> Maybe, absolutely no idea which one is best ;-)

I'd personally go with `tvos`

**Comment by sy6sy2** [comment]
The `TARGET_OS_IPHONE ` seems to be the cleanest way. But this modification would have an impact on both iOS and tvOS existing code, isn't is?
Don't know if Rechi is agree to replace all `TARGET_DARWIN_IOS ` by `TARGET_OS_IPHONE ` in the code. Or maybe I misunderstood a thing?

**Comment by kambala-decapitator** [comment]
you're absolutely correct :) you could already ask Rechi about that.

for now we can follow yab approach, and after our cmake and core PRs are merged, I can open a separate one that uses `TARGET_OS_IPHONE`.

**Comment by phunkyfish** [comment]
In the last PR he referenced a set of defines. Let me look it up.

**Comment by phunkyfish** [comment]
https://github.com/xbmc/xbmc/pull/15919#discussion_r276098856

**Comment by sy6sy2** [comment]
Yes, that's what kambala was referring to I think.

I will ask Rechi about his plan directly in the PR discussion.

**Comment by phunkyfish** [comment]
That didn’t really work.

From Rechi:

The reason I'm asking is the following comment from TargetConditionals.h in the platforms SDKs. Also most of the build system code looks the same. I was thinking to handle it like the different windowing for linux.

```
TARGET_OS_* 
These conditionals specify in which Operating System the generated code will
run.  Indention is used to show which conditionals are evolutionary subclasses.  

The MAC/WIN32/UNIX conditionals are mutually exclusive.
The IOS/TV/WATCH conditionals are mutually exclusive.


    TARGET_OS_WIN32           - Generated code will run under 32-bit Windows
    TARGET_OS_UNIX            - Generated code will run under some Unix (not OSX) 
    TARGET_OS_MAC             - Generated code will run under Mac OS X variant
       TARGET_OS_OSX          - Generated code will run under OS X devices
       TARGET_OS_IPHONE          - Generated code for firmware, devices, or simulator
          TARGET_OS_IOS             - Generated code will run under iOS 
          TARGET_OS_TV              - Generated code will run under Apple TV OS
          TARGET_OS_WATCH           - Generated code will run under Apple Watch OS
          TARGET_OS_BRIDGE          - Generated code will run under Bridge devices
       TARGET_OS_SIMULATOR      - Generated code will run under a simulator
       TARGET_OS_EMBEDDED       - Generated code for firmware
   
    TARGET_IPHONE_SIMULATOR   - DEPRECATED: Same as TARGET_OS_SIMULATOR
    TARGET_OS_NANO            - DEPRECATED: Same as TARGET_OS_WATCH

  +------------------------------------------------+
  |                TARGET_OS_MAC                   |
  | +---+  +-------------------------------------+ |
  | |   |  |          TARGET_OS_IPHONE           | |
  | |OSX|  | +-----+ +----+ +-------+ +--------+ | |
  | |   |  | | IOS | | TV | | WATCH | | BRIDGE | | |
  | |   |  | +-----+ +----+ +-------+ +--------+ | |
  | +---+  +-------------------------------------+ |
  +------------------------------------------------+
```

**Comment by sy6sy2** [comment]
> That didn’t really work.

What do you mean?

**Comment by phunkyfish** [comment]
I tried to link to the comment but it just brought you to the entire PR instead. Copy paste and worked much better.

**Comment by sy6sy2** [comment]
Ah ok!

So maybe we can wait for Rechi's answer in the PR.

Edit: I updated my comment in the PR discussion

**Comment by sy6sy2** [comment]
So, what I understand from Rechi answer:

* Only one PR with ALL modification for Kodi tvOS support
* Usage of `set(CORE_SYSTEM_NAME ios)` + `set(CORE_PLATFORM_NAME tvos)` in the Toolchain for Apple TV build
* Concerning `#define` preprocessor I am not very sure to understand...

**Comment by phunkyfish** [comment]
I think he means that TARGET_DARWIN_IPHONE is set for either iOS or tvOS to show they are related as well as their specific include.

He asked if there was a better name for TARGET_DARWIN_IPHONE as it’s not exactly suited as a family name for tvOS.

**Comment by kambala-decapitator** [comment]
@phunkyfish yes, correct. That's why I thought of the name like `TARGET_DARWIN_EMBEDDED`. Or maybe `TARGET_DARWIN_NONDESKTOP` would also do.

**Comment by phunkyfish** [comment]
Let’s ask Rechi what he thinks.

EDIT: asked on PR.

**Comment by phunkyfish** [comment]
`TARGET_DARWIN_EMBEDDED` it is.

So for tvOS that should be defined to denote it’s either iOS or tvOS and also define `TARGET_DARWIN_TVOS`.

Does that make sense @SylvainCecchetto?

**Comment by phunkyfish** [comment]
So based on your earlier 3 points they should be:

- Only one PR with ALL modification for Kodi tvOS support
- Usage of set(CORE_SYSTEM_NAME ios) + set(CORE_PLATFORM_NAME tvos) in the Toolchain for Apple TV build
- Concerning #define preprocessor `TARGET_DARWIN_EMBEDDED` and `TARGET_DARWIN_TVOS` for tvOS (and by inference iOS would define `TARGET_DARWIN_EMBEDDED` and `TARGET_DARWIN_IOS`)

**Comment by sy6sy2** [comment]
Sorry I just come back.
The plan seems clear to me, thank you for the 3 points above!

Maybe I should rename `ATV-cmake-generation` with other name like `ATV-PR` and use this branch to the final PR with ALL modifications?
May I keep the current PR open?

**Comment by phunkyfish** [comment]
I don’t think the branch name matters much. Just rename the PR I’d say and add everything else.

**Comment by phunkyfish** [comment]
Post here when you are happy with the branch and I’ll kick off a test build.

**Comment by sy6sy2** [comment]
Ok no problem, thank you ;-)

**Comment by kambala-decapitator** [comment]
`cmake/treedata/ios/subdirs.txt` also needs to be copied for tvOS and modified accordingly, I guess

**Comment by sy6sy2** [comment]
Hi all!
So, I'm sure that there is:
* Errors
* Missing things
* Wrong order commits

Anyway, this is a first try xD but this branch is up to date with upstream/master (rebase).

I will try to compile everything from scratch also.

Edit: As expected, dependencies build still works

Edit2: I am currently fixing things that Rechi highlighted, I will force push soon on this branch.

**Comment by sy6sy2** [comment]
Don't know if I broke something but I cannot build Kodi ATV with this branch ; error on `cores/AudioEngine/Skins/AESinkDARWINIOS.mm` file

**Comment by kambala-decapitator** [comment]
would you post the error? :)

**Comment by sy6sy2** [comment]
```
/Users/sylvain/Kodi_dev/kodi/xbmc/cores/AudioEngine/Sinks/AESinkDARWINIOS.mm:105:19: 
Unknown type name 'AudioSessionPropertyID'; did you mean 'AudioServicesPropertyID'?

/Users/sylvain/Kodi_dev/kodi/xbmc/cores/AudioEngine/Sinks/AESinkDARWINIOS.mm:284:45:
Use of undeclared identifier 'kAudioSessionProperty_PreferredHardwareIOBufferDuration'
```

15 errors

**Comment by kambala-decapitator** [comment]
you have old version. grab the latest from ATV branch: https://github.com/SylvainCecchetto/xbmc/blob/ATV/xbmc/cores/AudioEngine/Sinks/AESinkDARWINIOS.mm

**Comment by sy6sy2** [comment]
In `CMakeLists.txt` we have:

```cmake
core_add_subdirs_from_filelist(${CMAKE_SOURCE_DIR}/cmake/treedata/common/*.txt
                               ${CMAKE_SOURCE_DIR}/cmake/treedata/${CORE_SYSTEM_NAME}/*.txt)
```

It worked when `CORE_SYSTEM_NAME` was equal to `tvos` but now that we use `CORE_SYSTEM_NAME =ios` with `CORE_PLATFORM_NAME=tvos` then Cmake used `cmake/treedata/ios/subdirs.txt` instead of `cmake/treedata/tvos/subdirs.txt`.

Any idea on how to fix it without modifying `CMakeLists.txt`?

**Comment by phunkyfish** [comment]
How does it work for rbpi?

**Comment by sy6sy2** [comment]
It seems that it uses the same subdirs.txt file as linux

**Comment by phunkyfish** [comment]
I assume those files are different between iOS and tvOS.

I think CMakeLists.txt would need to be changed. Temp var with CORE_SYSTEM_NAME and then update it if CORE_PLATFORM_NAME is tvos.

I see CORE_PLATFORM_NAME has changed from appletvos to tvos. Will this cause any issues with the build? There are many things named with appletvos but not sure if they are created by us or are Xcode specific.

**Comment by sy6sy2** [comment]
This is my current dirty hack :-/

```cmake
# Subdirs
# Tempo hack
if(CORE_PLATFORM_NAME STREQUAL "tvos")
core_add_subdirs_from_filelist(${CMAKE_SOURCE_DIR}/cmake/treedata/common/*.txt
                               ${CMAKE_SOURCE_DIR}/cmake/treedata/${CORE_PLATFORM_NAME}/*.txt)
core_add_optional_subdirs_from_filelist(${CMAKE_SOURCE_DIR}/cmake/treedata/optional/common/*.txt
                                        ${CMAKE_SOURCE_DIR}/cmake/treedata/optional/${CORE_PLATFORM_NAME}/*.txt)
else()
core_add_subdirs_from_filelist(${CMAKE_SOURCE_DIR}/cmake/treedata/common/*.txt
                               ${CMAKE_SOURCE_DIR}/cmake/treedata/${CORE_SYSTEM_NAME}/*.txt)
core_add_optional_subdirs_from_filelist(${CMAKE_SOURCE_DIR}/cmake/treedata/optional/common/*.txt
                                        ${CMAKE_SOURCE_DIR}/cmake/treedata/optional/${CORE_SYSTEM_NAME}/*.txt)
endif()
```

I don't see any issue concerning CORE_PLATFORM_NAME yet.

So, I am able to compile Kodi on ATV-cmake-generation branch (I will push latest changes on GitHub). (not tested on my Apple TV yet).
But I think that there is duplicated code in windowing between iOS and tvOS that we need to modify.

**Comment by phunkyfish** [comment]
Did you get a chance to try and run it on your apple TV?

**Comment by sy6sy2** [comment]
I would like, but once again I am stuck with this fucking `no code signature found` -_-'
But this time, the "delete" fix don't work

**Comment by phunkyfish** [comment]
That happens to me sometimes too. I just delete the kodi-build dir and regenerate the project.

**Comment by sy6sy2** [comment]
I will try again, thank you ;-)

**Comment by sy6sy2** [comment]
Still have the issue :-(

**Comment by phunkyfish** [comment]
Maybe an issue with generation of the project. Will kick off a build now, is the branch updated?

**Comment by sy6sy2** [comment]
Yes maybe ... I will try tomorrow to build and run the ATV branch to see if I have still the issue.

Yes the branch is up to date. There is just an issue with the bundle identifier that I will fix tomorrow

**Comment by phunkyfish** [comment]
Should probably also include the link to the build doc in the PR.

**Comment by kambala-decapitator** [comment]
@SylvainCecchetto please move setting bundle ID from ArchSetup.cmake right before this line: https://github.com/SylvainCecchetto/xbmc/blob/ATV-cmake-generation/CMakeLists.txt#L351

**Comment by kambala-decapitator** [comment]
tried to generate project from the latest commit:

```-- CMake Version: 3.12.2
CMake Error at cmake/scripts/common/Platform.cmake:35 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:32 (include)

CMake Error at cmake/scripts/common/Platform.cmake:36 (message):
  invalid CORE_PLATFORM_NAME: tvos

  Valid platforms:
Call Stack (most recent call first):
  CMakeLists.txt:32 (include)

-- Configuring incomplete, errors occurred!```

this fails: `if(EXISTS ${CMAKE_SOURCE_DIR}/cmake/platform/${CORE_SYSTEM_NAME}/${CORE_PLATFORM_NAME_LC}.cmake)`

as now there's no `cmake/platform/tvos` dir

**Comment by sy6sy2** [comment]
Is anybody have an idea on how to fix this "Tempo hack" (https://github.com/xbmc/xbmc/pull/15956/commits/f821dba3046bb4e88da84c07751ac7bcb3e041a4#r278421327) properly? Thank you!

**Comment by phunkyfish** [comment]
Either set CORE_PLATFORM_NAME to CORE_SYSTEM_NAME for everything except tvOS and use that or use a temp var which gets set to CORE_SYSTEM_NAME except in the case of where CORE_PLATFORM_NAME is tvOS

**Comment by phunkyfish** [comment]
Actually that would break raspberry pi. So all
I have is the temp var approach.

**Comment by phunkyfish** [comment]
Branch will need a rebase as currently pvr addons don’t build as they have been branched to Matrix.

**Comment by sy6sy2** [comment]
Yes there is the temp var approach, but I think Rechi wants that we not touch this part of the CmakeList file.
But I will try ;-)

Yep, I will rebase now!

**Comment by sy6sy2** [comment]
I force pushed the temp var approach and the branch is up to date with master.

**Comment by kambala-decapitator** [comment]
what if you temporarily set `CORE_SYSTEM_NAME` to expected value and then set it back?

    if(CORE_PLATFORM_NAME STREQUAL "tvos")
      set(CORE_SYSTEM_NAME_ORIGNIAL ${CORE_SYSTEM_NAME})
      set(CORE_SYSTEM_NAME "tvos")
    endif()
    core_add_subdirs_from_filelist(${CMAKE_SOURCE_DIR}/cmake/treedata/common/*.txt
    	                               ${CMAKE_SOURCE_DIR}/cmake/treedata/${CORE_SYSTEM_NAME}/*.txt)
    core_add_optional_subdirs_from_filelist(${CMAKE_SOURCE_DIR}/cmake/treedata/optional/common/*.txt
                                            ${CMAKE_SOURCE_DIR}/cmake/treedata/optional/${CORE_SYSTEM_NAME}/*.txt)
    if(CORE_PLATFORM_NAME STREQUAL "tvos")
      set(CORE_SYSTEM_NAME ${CORE_SYSTEM_NAME_ORIGNIAL})
    endif()

**Comment by sy6sy2** [comment]
Yes, sounds a better alternative as the temp var approach.
I will update this file. thank you.

**Comment by sy6sy2** [comment]
Rechi said "This is still a hack" :-/
I guess that we need to find another solution without modifying CmakeLists.txt

**Comment by phunkyfish** [comment]
Ask him what he suggests?

**Comment by kambala-decapitator** [comment]
I think the right approach is to modify `cmake/treedata/ios/subdirs.txt` that it contains `${CORE_PLATFORM_NAME}` where appropriate. probably it would require small modification of `core_add_subdirs_from_filelist` and `core_add_optional_subdirs_from_filelist` macros in `cmake/scripts/common/Macros.cmake` as well.

**Comment by sy6sy2** [comment]
I thought about that actually. So I need to adapt `core_add_subdirs_from_filelist ` and `core_add_optional_subdirs_from_filelist` in order to replace the var `${CORE_PLATFORM_NAME}` by the actual value.

**Comment by kambala-decapitator** [comment]
yep. But maybe also ask Rechi on his view on the solution now, he might offer a better one.

**Comment by sy6sy2** [comment]
But I cannot do something like 
`xbmc/windowing/${CORE_PLATFORM_NAME}                    windowing/${CORE_PLATFORM_NAME}`
because with iOS this var is not set.

**Comment by kambala-decapitator** [comment]
then we need to set it...

or wait, there're some cmake generator expressions that can use conditions, so we can write in a single statement "if CORE_PLATFORM_NAME is set, then use it, otherwise use CORE_SYSTEM_NAME"

**Comment by sy6sy2** [comment]
Another solution, but I doubt is a good one, would be to use the same sources files for iOS and tvOS. So we have only one folder in `xbmc/platform/darwin/` and `xbmc/windowing/` but a lot of if/else macro :-/

**Comment by sy6sy2** [comment]
> or wait, there're some cmake generator expressions that can use conditions, so we can write in a single statement "if CORE_PLATFORM_NAME is set, then use it, otherwise use CORE_SYSTEM_NAME"

Do you mean, using this thing in CmakeLists? But it could break raspberry no?

**Comment by kambala-decapitator** [comment]
no-no, in ios/subdirs.txt

**Comment by kambala-decapitator** [comment]
> Another solution, but I doubt is a good one, would be to use the same sources files for iOS and tvOS. So we have only one folder in `xbmc/platform/darwin/` and `xbmc/windowing/` but a lot of if/else macro :-/

does rbpi use this approach?

**Comment by sy6sy2** [comment]
Yes, bpi uses the `CORE_PLATFORM_NAME ` var:
```cmake
if(OS STREQUAL linux)
  set(CMAKE_SYSTEM_NAME Linux)
  set(CORE_SYSTEM_NAME linux)
  if(PLATFORM STREQUAL raspberry-pi)
    set(CORE_PLATFORM_NAME rbpi)
[...]
```

But bpi uses the same subdirectories as Linux so the issue with CmakeList does not appear :-/

**Comment by kambala-decapitator** [comment]
sorry, I mean in code:
> So we have only one folder in xbmc/platform/darwin/ and xbmc/windowing/ but a lot of if/else macro

**Comment by sy6sy2** [comment]
Hum, I don't understand how it works for rbpi because there is a folder `xbmc/windowing/rbpi` but not a file `cmake/treedata/rbpi/subdirs.txt`

**Comment by sy6sy2** [comment]
Ok I understand, this is done by CmakeLists.txt in `xbmc/windowing` folder:

```cmake
set(SOURCES GraphicContext.cpp
            OSScreenSaver.cpp
            Resolution.cpp
            WinSystem.cpp)

set(HEADERS GraphicContext.h
            OSScreenSaver.h
            Resolution.h
            WinEvents.h
            WinSystem.h
            XBMC_events.h
            VideoSync.h)

if(CORE_PLATFORM_NAME_LC STREQUAL rbpi)
  add_subdirectory(rpi)
endif()

core_add_library(windowing)
```

Maybe we could use the same approach?

**Comment by sy6sy2** [comment]
So what I can do is:
* Set `CORE_PLATFORM_NAME` to `ios` or `tvos`
* Put in `cmake/treedata/ios/subdirs.txt` only folders/files that are common to iOS and tvOS
* Use the `if(CORE_PLATFORM_NAME_LC STREQUAL xxxx)  add_subdirectory(xxxx) endif()` approach in `CmakeLists.txt` files for files that are not the same for IOS and tvOS.

Then we do not need to modify the main `CmakeLists.txt` file.
What do you think?

**Comment by kambala-decapitator** [comment]
personally I think we should follow the rbpi approach. Could you forward your comment to Rechi to find out his opinion?

**Comment by phunkyfish** [comment]
Agreed, I’d say rbpi approach is probably the right one.

**Comment by kambala-decapitator** [comment]
created https://github.com/xbmc/xbmc/pull/16015 for the iOS audio sink change

**Comment by kambala-decapitator** [comment]
it seems that after our latest cmake hack build started failing...

**Comment by sy6sy2** [comment]
Really? I will try tomorrow, time to sleep ;-)
In any case this hack should be removed soon if Rechi is agree with the rpi approach!

**Comment by phunkyfish** [comment]
Rechi’s reply makes perfect sense now that I see it.

**Comment by sy6sy2** [comment]
Yes! Totally agree.
Now we can wait for "sub-PRs" to be merged (see https://github.com/SylvainCecchetto/xbmc/issues/52 discussion).
After that, we will have the final PR (this one) with only tvOS support.
