### ISSUE TITLE
Apple TV GitHub branches summary

### ISSUE THREAD

**Issue by sy6sy2** [SylvainCecchetto/xbmc#60]
## Disclaimer:
**Kodi 19 for Apple TV is still in development and many things do not work yet. If you want a daily Kodi app please follow this [tutorial](https://forum.kodi.tv/showthread.php?tid=245978). If you really want to try Kodi 19 from one of the above branches (maybe to find any bug or to help in the development), be sure to have the necessary skills to do it and do not expect any "basic" support here. And last but not least, please do not share any generated `deb` from this branches! *Official* Kodi 19 version for Apple TV will be available for end users sooner or later, please be patient and use Kodi 17.**
<br>

Just a little reminder of all the current branches where there is some Apple TV progress (for us and for people who want to help or try to build).

* **https://github.com/fuzzard/xbmc/tree/master_darwin-embedded-ATV**
    * The most up-to-date branch concerning Apple TV support for Kodi 19
    * This is where we need to open PR for any new feature, improvement or bug fix
    * This is the branch to use for any user who want to try Kodi 19 on Apple TV
    * **Users: this is a work in progress branch!**
<br>

* **https://github.com/Memphiz/xbmc/tree/yab**
    * The (old) Memphiz's branch that contains Kodi 17 Apple TV working code
    * If you want to port an existing feature of Apple TV Kodi 17 version, this where you to find it
<br>

* **https://github.com/MrMC/mrmc**
    * Official repo of MrMC (Kodi fork available on the tvOS App Store)
    * This is where we can find some feature to port like the focus engine feature
<br>

(Feel free to ask me to update this post)

**Comment by sasagr** [comment]
hello beloved developers, I will be willing to try to first (since I m already using the other two :) ) but before I start I would like to ask if with the current status at least the xcode building process works sucessfully

**Comment by sy6sy2** [comment]
Hi sasagr, I have not tested since the last commits but the building process should works ;-)
You can find the detailed documentation in `xbmc/docs/README.tvOS.md`.

**Comment by sasagr** [comment]
after 4 hours... of dependencies and binary addons build I got this error (pasting the last a few lines from terminal):

```
Scanning dependencies of target visualization.spectrum
[ 75%] Creating directories for 'visualization.spectrum'
[ 75%] No download step for 'visualization.spectrum'
[ 75%] No patch step for 'visualization.spectrum'
[ 75%] No update step for 'visualization.spectrum'
[ 75%] Performing configure step for 'visualization.spectrum'
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking to see if CXX compiler accepts flag -flto
-- Checking to see if CXX compiler accepts flag -flto - yes
-- Found PkgConfig: /Users/Shared/xbmc-depends/x86_64-darwin17.7.0-native/bin/pkg-config (found version "0.28") 
-- Checking for module 'glesv2'
--   No package 'glesv2' found
-- Could NOT find OpenGLES2 (missing: OPENGLES2_INCLUDE_DIRS OPENGLES2_gl_LIBRARY OPENGLES2_egl_LIBRARY) 
CMake Error at CMakeLists.txt:70 (message):
  No rendering API found.  Bailing


-- Configuring incomplete, errors occurred!
See also "/Users/xxx/Desktop/kodi/tools/depends/target/binary-addons/appletvos12.1_arm64-target-debug/visualization.spectrum-prefix/src/visualization.spectrum-build/CMakeFiles/CMakeOutput.log".
make[4]: *** [visualization.spectrum-prefix/src/visualization.spectrum-stamp/visualization.spectrum-configure] Error 1
make[3]: *** [CMakeFiles/visualization.spectrum.dir/all] Error 2
make[2]: *** [CMakeFiles/visualization.spectrum.dir/rule] Error 2
make[1]: *** [visualization.spectrum] Error 2
touch .installed-appletvos12.1_arm64-target-debug
```

not sure if I can proceed with next step (Xcode build)

**Comment by sy6sy2** [comment]
Yes, don’t expect all binary addons building correctly. 
ATM only dependencies and Kodi itself work ;)

**Comment by sasagr** [comment]
ok. trying to build with Xcode 

ps: I had to change as per following according to my actual folders names:
 /Users/Shared/xbmc-depends/x86_64-darwin17.7.0-native/bin/cmake -G Xcode -DCMAKE_TOOLCHAIN_FILE=/Users/Shared/xbmc-depends/appletvos12.1_arm64-target-debug/share/Toolchain.cmake ../kodi

**Comment by sasagr** [comment]
by the way I don't want to report my findings in this discussion (or at all) if you find this is not the right location. pls guide me

**Comment by sasagr** [comment]
ok, build succeeded, created deb file, signed, installed on my atv4. It crashes upon launch. Cool icon by the way

**Comment by pogarek** [comment]
which branch and repo have you used ? it shouldn't crash - at least it works for us till this point. 
We , even, have video playing

**Comment by sasagr** [comment]
git clone -b master_darwin-embedded-ATV https://github.com/fuzzard/xbmc/ kodi

I have only one doubt... I m using Xcode Version 10.1 (10B61) with High Sierra 10.13.6

**Comment by pogarek** [comment]
hm, branch seems to be ok. I haven't built it since a few days, but I don't expect issues. Let me test it

**Comment by pogarek** [comment]
I built all from scratch and kodi started successfully. MacOS 10.14.4, XCode 10.2.1, tvos 12.3

**Comment by sasagr** [comment]
in this case could Xcode 10.1 be the limit? I cannot install the 10.2 or higher on my old MCBP.
If this is the case at the moment I can only wait for a pre-built deb to try

**Comment by sy6sy2** [comment]
Maybe you can try to run Kodi directly from Xcode without generate the deb?

**Comment by kambala-decapitator** [comment]
> in this case could Xcode 10.1 be the limit?

not at all, I also can't install Mojave on my mbp and all runs fine with Xcode 10.1

**Comment by sasagr** [comment]
![1](https://user-images.githubusercontent.com/3427877/57854387-cc013b80-77f0-11e9-8287-1f31b1bfd60b.png)
![2](https://user-images.githubusercontent.com/3427877/57854392-cf94c280-77f0-11e9-9719-abdfe4aa411f.png)

**Comment by sy6sy2** [comment]
You need to select `kodi` target and not `ALL_BUILD`, then `CMD-R` to run

**Comment by kambala-decapitator** [comment]
and you also shouldn't build for simulator, as most probably depends were configured for device :)

**Comment by phunkyfish** [comment]
@SylvainCecchetto in your first post it should be Kodi 19 ;)

**Comment by phunkyfish** [comment]
@sasagr you should also select you actual ATV device along with the kodi target if you are using CMD-R.

**Comment by sasagr** [comment]
![33](https://user-images.githubusercontent.com/3427877/57862819-a6c8f900-7801-11e9-8455-1d47917de657.png)

**Comment by kambala-decapitator** [comment]
you can cancel and just run from your ATV now

**Comment by sasagr** [comment]
there is no sign of the new kodi installation on the ATV though on Xcode is see
![qwe](https://user-images.githubusercontent.com/3427877/57863607-12f82c80-7803-11e9-8f12-744772bce93a.png)

and looking at the code signing warning I realised that I did not do anything in Xcode to manually sign it. I mean since I launched the the project from kodi-build folder I don't see the section where I should sign it and generate provisioning file. I think this discussion it may going a bit out of thread at this point  :(

**Comment by phunkyfish** [comment]
@sasagr are you using a free account or paid dev account?

**Comment by sasagr** [comment]
For this a free account

**Comment by phunkyfish** [comment]
Ok, then you can let Xcode do automatic signing. You should be able to enable that in the general tab of the kodi target.

**Comment by sasagr** [comment]
I signed the app within xcode with my free account, the build seems to be successful but the app is not installed in the Apple TV. Something is wrong. I m trying to build it another time otherwise pls let me know if there is a way I can extract a deb from the xcode build so I can try to side load it.
Otherwise I will try a fresh from scratch build rebuilding again all the dependencies,... in case something went missing

**Comment by pogarek** [comment]
hm. maybe we could post a deb somewhere, refreshing it 1-2 times per week and make a note, that this is a alpha version, without addons and we don't recommend to use it as an upgrade ?

We could pin issue here and publish deb on wetransfer.com or something similar

**Comment by phunkyfish** [comment]
No, we should not provide a deb file. Official builds only for the community I think.

Once something comes from Jenkins that should be the first community build.

**Comment by phunkyfish** [comment]
@sasagr can you post a screenshot of the general tab of your kodi target from Xcode before selecting run?

Also what version of tvOS are you running?

**Comment by sasagr** [comment]
![ss](https://user-images.githubusercontent.com/3427877/57909818-7c704d80-788c-11e9-8d6a-537a03475aa6.png)

tvOS 12.2.1
Model A1625

just finished a new build attempt. I get a successful message but the app is not there. I even removed the 17.6 version I installed previously in case of conflict.

**Comment by sy6sy2** [comment]
No need to remove the 17.6 version if you use a different App ID.
Did you hit `CMD-R` after your `CMD-B`?

**Comment by sasagr** [comment]
CMD-R

**Comment by sasagr** [comment]
or the big PLAY button on the top left side of the window

**Comment by sy6sy2** [comment]
Yes this Is the same thing

**Comment by phunkyfish** [comment]
Ok, and if you manually install it. I.e.

Go to devices and simulators, hit the plus on the office ATV and go to kodi-build/build/Debug-appletvos and select Kodi.app 

What happens?

**Comment by sasagr** [comment]
that worked!!

**Comment by sasagr** [comment]
now is there a way I can get the deb from it?

**Comment by phunkyfish** [comment]
Yes, just build the deb target.

**Comment by phunkyfish** [comment]
@pogarek where does the deb file get created. Afraid i’ve Never used it myself 😉

**Comment by sasagr** [comment]
> Yes, just build the deb target.

I build it to my actual device (Office) or Generic tv device?

**Comment by sy6sy2** [comment]
@sasagr If you generate the deb file, please do not share anywhere (see first post) Thank you 😉
No matter I think, but you can keep your real device

**Comment by phunkyfish** [comment]
If you could post the deb file location back here I’ll add it to the documentation

**Comment by sasagr** [comment]
I have to find it first :)  
by the way... thanks for all your support. I will continue to follow you and use me as dummy test :) if you need :) 
Otherwise i will be looking for the first official releases or test-builds that will be published

**Comment by pogarek** [comment]
if I recall correctly, deb file would be there : kodi-build/tools/darwin/packaging

**Comment by sasagr** [comment]
yes it is there

**Comment by sasagr** [comment]
I installed the deb that was created for the ATV4 in my other ATV4K and I see the display is at 1080 and no other options to make it higher. I guess this is because it was built specifically for the ATV4 (non 4K).
Will make a build for the 4K version too. If this is the case maybe the right way it could be to build it to the generic device (I assume it will be good for both versions).

**Comment by phunkyfish** [comment]
I’m not sure, but try it and let us know!

**Comment by sasagr** [comment]
confirmed. Build it for ATV4K, installed it (for some reason it does not install automatically on the device and I have to do it from the +) and the display now is @2160.
Did not try the generic build though but probably it should be good for both version.. you may know better.

**Comment by URBANsUNITED** [comment]
Hi!
Is it worth to build a snap already? Are we able to watch our movies in x264 and x265 or is this not yet working? Don't want to spend hours for compiling and frustration.
Maybe someone can share his file for a ATV4k?
Thanks in advance!!
Cheers

URBANsUNITED

**Comment by phunkyfish** [comment]
Please see the disclaimer above, happy for you to build this yourself but no builds will be available until it’s officially built by kodi’s Jenkins server, it could take some time to get to that point.

It works with x264, have not tested x265. Audio is limited to stereo, no UI sounds and binary addons are not available yet.

**Comment by pogarek** [comment]
Build instructions: https://github.com/xbmc/xbmc/blob/master/docs/README.tvOS.md . You can ignore binary addons at this moment.

**Comment by eugene2878** [comment]
Is this possible to compile with xcode 9? Gives me an error `configure: error: C++ compiler cannot create executables See config.log' for more details`

**Comment by kambala-decapitator** [comment]
@eugene2878 the error doesn't seem Xcode version related. Have you checked the actual error?

**Comment by phunkyfish** [comment]
Did you install the command line tools?

**Comment by eugene2878** [comment]
> Did you install the command line tools?
Not sure followed readme.tvos.md. Can you expand on this?

**Comment by phunkyfish** [comment]
This piece: ```WARNING: Start Xcode after installation finishes. You need to accept the licenses and install missing components.```

**Comment by eugene2878** [comment]
Would I be able to run Kodi on tvOS 11 or atleast on tvOS 12.1 if compiled on latest xcode with tvOS 12.2 profile?

**Comment by eugene2878** [comment]
Xcode 9.4.1 
`MBP-Late-13:depends eugene$ ./configure --host=arm-apple-darwin --with-platform=tvos
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
checking build system type... x86_64-apple-darwin18.5.0
checking host system type... arm-apple-darwin
checking whether the C++ compiler works... no
configure: error: in `/Users/eugene/kodi/tools/depends':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
`

**Comment by phunkyfish** [comment]
Yes, I think so. If you just connect your device and compile directly for your device it should figure out the right combo for you.

Apologies I didn’t reply sooner, thought I had replied!

**Comment by URBANsUNITED** [comment]
I am curious.
What is the status of Kodi atm?
Are we able to run  x264 and x265 files with at least DTS support and proper 24Hz switching?
Have a paid dev account for proper signing.
Thanks

**Comment by kambala-decapitator** [comment]
I think we should start prioritising issues, as currently I don't really understand what is the most important that is missing from ATV. We have a bunch of open issues, but all of those don't look serious.

Do we have any blockers right now? Besides waiting for the cmake/Xcode changes in iOS PR.

**Comment by fuzzard** [comment]
How we are handling the audio pr is probably the biggest possible blocker from master.

Feature wise, the best thing may be around auto refresh rate/HDR switching being implemented, which I don't have anything close to a PR ready

**Comment by phunkyfish** [comment]
I think we should separate it out for tvOS, as with the current regressions (also in MrMc) for iOS it won’t get approved.

**Comment by kambala-decapitator** [comment]
I agree that for now we can use separate audio sink implementation for tvOS.

**Comment by phunkyfish** [comment]
So then it will just be the cmake PR holding things up. So just some renaming on that and we should be good.

**Comment by sy6sy2** [comment]
Closing because tvOS support is now part of https://github.com/xbmc/xbmc/tree/master
