### ISSUE TITLE
can't close No Favourites window

### ISSUE THREAD

**Issue by kambala-decapitator** [SylvainCecchetto/xbmc#68]
pressing Menu closes app instead of closing the window.

Probably this debug output helps:
> Control 450 in window 10134 has been asked to focus, but it can't

![Screen Shot 2019-06-01 at 17 38 27](https://user-images.githubusercontent.com/1557784/58749956-e267f200-8494-11e9-9199-934a0cc76487.png)

**Comment by sasagr** [comment]
I confirm the same issue

**Comment by sasagr** [comment]
this is happening also with the Power Options window

**Comment by fuzzard** [comment]
Fixed by the following commit

https://github.com/fuzzard/xbmc/commit/74af0aa0f69f039868518d5e8f5d4a898e028764

**Comment by kambala-decapitator** [comment]
@fuzzard this was in py3 branch, now I've added it to the main one too
