### ISSUE TITLE
error installing deb package

### ISSUE THREAD

**Issue by kambala-decapitator** [SylvainCecchetto/xbmc#72]
A guy PM'd me on the forum asking for deb, then he managed to compile app and package deb on his own, but that fails to install with ssh:

```
root@ (/tmp)# dpkg -i org.xbmc.kodi-tvos64_19.0.deb
dpkg: error processing archive org.xbmc.kodi-tvos64_19.0.deb (--install):
package architecture (appletvos-arm) does not match system (darwin-arm64)
Errors were encountered while processing:
```

**Comment by fuzzard** [comment]
Most likely need to get the following changed

https://github.com/fuzzard/xbmc/blob/299f285b03b3c8cf18def58cd7a3013151555b1b/tools/darwin/packaging/darwin_embedded/mkdeb-darwin_embedded.sh.in#L92

Leave it as darwin-arm maybe.

Master has the following

https://github.com/xbmc/xbmc/blob/9d117ae9faa7f5591205004249341394897fd427/tools/darwin/packaging/darwin_embedded/mkdeb-darwin_embedded.sh.in#L89

So you could maybe try change it to iphoneos-arm and see what happens.

**Comment by sy6sy2** [comment]
Can this guy send me the deb, I can try to install it on my jailbroken iPhone 7?

**Comment by kambala-decapitator** [comment]
@SylvainCecchetto you want to try to install tvOS package on iPhone? :)

**Comment by sy6sy2** [comment]
-_-' ... You right, it seems difficult xD

**Comment by sy6sy2** [comment]
Fixed by https://github.com/xbmc/xbmc/pull/17707 and https://github.com/xbmc/xbmc/pull/18315
