### ISSUE TITLE
It takes too long to trigger long press 

### ISSUE THREAD

**Issue by kambala-decapitator** [SylvainCecchetto/xbmc#74]
I guess my last gesture changes broke something a bit, will check.

**Comment by fuzzard** [comment]
yeah, long press for my cec (not siri remote) has been really long for a while now. Didnt know if it was because of a cec remote, or just remote handling in general for it.

**Comment by kambala-decapitator** [comment]
brought back one hunk that I removed, but not sure if it got better...

**Comment by kambala-decapitator** [comment]
solved it now: just removed all the legacy code responsible for normal select inside the long select handler.
